services:
  app:
    image: ci-ramadan:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci-ramadan-v1
    restart: unless-stopped
    ports:
      - "9001:9000"
    env_file:
      - .env.example
    volumes:
      - ./:/var/www/html
    entrypoint: ["/var/www/html/docker-app-entrypoint.sh"]
    networks:
      - ci-ramadan-network
  
  nginx:
    image: nginx:stable-alpine
    container_name: ci-ramadan-nginx-v1
    restart: unless-stopped
    ports:
      - "8091:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
      - ./docker-nginx-entrypoint.sh:/var/www/html/docker-nginx-entrypoint.sh
    depends_on:
      - app
    entrypoint: ["/var/www/html/docker-nginx-entrypoint.sh"]
    networks:
      - ci-ramadan-network


networks:
  ci-ramadan-network:
    driver: bridge
